# Generated by Django 2.2.12 on 2020-05-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField()),
                ('rank', models.CharField(choices=[('Distinguished', 'Distinguished'), ('professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Master Instructor', 'Master Instructor'), ('Senior Instructor', 'Senior Instructor'), ('Instructor', 'Instructor'), ('Research Associate', 'Research Associate'), ('Lecturer', 'Lecturer')], default='LECTURER', max_length=32)),
            ],
        ),
    ]
